name: Workflow teste

 on:
   push:
     branches:
    
   schedule:
     - cron: '0 * * * *'  
    jobs:
      build:
         runs-on: ubuntu-latest
       steps:
        - name: 
          uses: actions/checkout@v2

     - name: Build
     run: echo "Workflow concluído com sucesso!"
