name: Workflow teste

on:
  push:
    branches:
      - main  

  schedule:
    - cron: '0 * * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Workflow concluído com sucesso!"
